// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCHBbUv7ZzEAtB7F-SRvfmGkZoD9CQ2uY',
    appId: '1:47980364028:web:3b3075486c9182561c9779',
    messagingSenderId: '47980364028',
    projectId: 'dozer-15e08',
    authDomain: 'dozer-15e08.firebaseapp.com',
    storageBucket: 'dozer-15e08.appspot.com',
    measurementId: 'G-Z6XTCTK1FC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLqqa_KXxhdPrXVTYg81DO8Yy7SmAz0U',
    appId: '1:47980364028:android:4ed00886ea8af4801c9779',
    messagingSenderId: '47980364028',
    projectId: 'dozer-15e08',
    storageBucket: 'dozer-15e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8gVtk0ZrRclP-sRk6rCENoCFEh3V1mk',
    appId: '1:47980364028:ios:799aaced23fa92a71c9779',
    messagingSenderId: '47980364028',
    projectId: 'dozer-15e08',
    storageBucket: 'dozer-15e08.appspot.com',
    iosBundleId: 'com.example.dozerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb8gVtk0ZrRclP-sRk6rCENoCFEh3V1mk',
    appId: '1:47980364028:ios:799aaced23fa92a71c9779',
    messagingSenderId: '47980364028',
    projectId: 'dozer-15e08',
    storageBucket: 'dozer-15e08.appspot.com',
    iosBundleId: 'com.example.dozerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCHBbUv7ZzEAtB7F-SRvfmGkZoD9CQ2uY',
    appId: '1:47980364028:web:58918cd1b07d3ab61c9779',
    messagingSenderId: '47980364028',
    projectId: 'dozer-15e08',
    authDomain: 'dozer-15e08.firebaseapp.com',
    storageBucket: 'dozer-15e08.appspot.com',
    measurementId: 'G-TT5HJLS4FY',
  );
}
